from __future__ import annotations

import math
import re
import struct
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import numpy as np


MODEL_DIR = Path(__file__).resolve().parent
OUT_MESH_DIR = MODEL_DIR / "generated_stl"
OUT_XML = MODEL_DIR / "fish_2d_stl.xml"

WIRE_RADIUS = 0.0375

ACTIVE_RANGE_DEG = 15.0
ACTIVE_STIFFNESS = 1.041
ACTIVE_DAMPING = 0.05

TAIL_RANGE_DEG = 25.0
TAIL_STIFFNESS = 0.18
TAIL_DAMPING = 0.02

CENTRE_MASS = 2.5
VERTEBRA_MASS = 0.05
TAIL_TOTAL_MASS = 0.5

TAIL_SEG_COUNT = 4

WATER_DENSITY = 850.0
WATER_VISCOSITY = 0.0007
POOL_LENGTH = 5.0
POOL_WIDTH = 3.0
POOL_DEPTH = 1.5
POOL_WALL_THICKNESS = 0.05
POOL_HALF_LENGTH = POOL_LENGTH / 2.0
POOL_HALF_WIDTH = POOL_WIDTH / 2.0
POOL_HALF_DEPTH = POOL_DEPTH / 2.0

# In the real mechanism the neighboring connector axes alternate orthogonally.
# For the 2D yaw-only model, some adjacent parts can be treated as a welded rigid set.
# The grouping below follows the user's latest mechanical simplification:
# front: [1], [2,3], [4,5], [6,7,8], [9,head]
# back:  [1], [2,3], [4,5], [6,7,8], [9,joint_tail]
FRONT_WELDED_CHILDREN = {3, 5, 7, 8}
BACK_WELDED_CHILDREN = {3, 5, 7, 8}
HEAD_WELDED_TO_FRONT = True
JOINT_TAIL_WELDED_TO_BACK = True

ROOT_DAMPING = 0.4
ROOT_ARMATURE = 0.01
SERVO_HALF_RANGE_RAD = 1.1
SERVO_HALF_RANGE_DEG = math.degrees(SERVO_HALF_RANGE_RAD)
SERVO_RADIUS = WIRE_RADIUS
SERVO_DAMPING = 0.2
SERVO_ARMATURE = 0.001
SERVO_KP = 120.0

VISUAL_RGBA = {
    "centre": "0.18 0.22 0.33 1",
    "vertebra": "0.20 0.54 0.81 1",
    "head": "0.10 0.37 0.64 1",
    "joint_tail": "0.17 0.56 0.56 1",
    "tail": "0.88 0.75 0.44 1",
}


def f(value: float) -> str:
    return f"{value:.6f}".rstrip("0").rstrip(".")


def vec3(values: Iterable[float]) -> str:
    x, y, z = values
    return f"{f(x)} {f(y)} {f(z)}"


def indent(lines: list[str], level: int) -> list[str]:
    prefix = "  " * level
    return [prefix + line if line else "" for line in lines]


@dataclass
class MeshInfo:
    name: str
    file_name: str
    triangles: np.ndarray
    bbox_min: np.ndarray
    bbox_max: np.ndarray
    center: np.ndarray
    volume: float

    @property
    def size(self) -> np.ndarray:
        return self.bbox_max - self.bbox_min

    @property
    def half_size(self) -> np.ndarray:
        return self.size / 2.0


def read_binary_stl(path: Path) -> np.ndarray:
    data = path.read_bytes()
    if len(data) < 84:
        raise ValueError(f"STL too small: {path}")

    tri_count = struct.unpack("<I", data[80:84])[0]
    expected = 84 + tri_count * 50
    if expected != len(data):
        raise ValueError(f"Only binary STL is supported: {path}")

    tris = np.empty((tri_count, 3, 3), dtype=np.float64)
    offset = 84
    for idx in range(tri_count):
        values = struct.unpack("<12fH", data[offset : offset + 50])
        tris[idx, 0, :] = values[3:6]
        tris[idx, 1, :] = values[6:9]
        tris[idx, 2, :] = values[9:12]
        offset += 50
    return tris


def write_binary_stl(path: Path, triangles: np.ndarray) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    header = b"Generated by rebuild_fish_from_stl.py".ljust(80, b" ")
    payload = bytearray(header)
    payload.extend(struct.pack("<I", int(len(triangles))))

    for tri in triangles:
        v1 = tri[1] - tri[0]
        v2 = tri[2] - tri[0]
        normal = np.cross(v1, v2)
        norm = np.linalg.norm(normal)
        if norm > 0:
            normal = normal / norm
        else:
            normal = np.zeros(3, dtype=np.float64)
        record = (
            float(normal[0]),
            float(normal[1]),
            float(normal[2]),
            float(tri[0, 0]),
            float(tri[0, 1]),
            float(tri[0, 2]),
            float(tri[1, 0]),
            float(tri[1, 1]),
            float(tri[1, 2]),
            float(tri[2, 0]),
            float(tri[2, 1]),
            float(tri[2, 2]),
            0,
        )
        payload.extend(struct.pack("<12fH", *record))

    path.write_bytes(payload)


def transform_to_model(points: np.ndarray, origin_mm: np.ndarray) -> np.ndarray:
    shifted = points - origin_mm
    # Original assembly axis is +Y from head to tail. Rotate +90 deg around Z so:
    # head direction (-Y) becomes +X and the model matches the prompt convention.
    x = -shifted[..., 1]
    y = shifted[..., 0]
    z = shifted[..., 2]
    return np.stack((x, y, z), axis=-1) * 0.001


def mesh_info(name: str, file_name: str, triangles: np.ndarray) -> MeshInfo:
    pts = triangles.reshape(-1, 3)
    bbox_min = pts.min(axis=0)
    bbox_max = pts.max(axis=0)
    center = (bbox_min + bbox_max) / 2.0
    return MeshInfo(
        name=name,
        file_name=file_name,
        triangles=triangles,
        bbox_min=bbox_min,
        bbox_max=bbox_max,
        center=center,
        volume=mesh_volume(triangles),
    )


def mesh_volume(triangles: np.ndarray) -> float:
    # STL winding can be inconsistent, so accumulate signed tetra volumes
    # and take the absolute value at the end.
    v0 = triangles[:, 0, :]
    v1 = triangles[:, 1, :]
    v2 = triangles[:, 2, :]
    signed_volume = np.einsum("ij,ij->i", v0, np.cross(v1, v2)).sum() / 6.0
    return abs(float(signed_volume))


def make_local_mesh(source_path: Path, mesh_name: str) -> MeshInfo:
    source_tris = read_binary_stl(source_path)
    pts = source_tris.reshape(-1, 3)
    bbox_min = pts.min(axis=0)
    bbox_max = pts.max(axis=0)
    center = (bbox_min + bbox_max) / 2.0
    local_tris = transform_to_model(source_tris, center)
    file_name = f"{mesh_name}.stl"
    write_binary_stl(OUT_MESH_DIR / file_name, local_tris)
    return mesh_info(mesh_name, file_name, local_tris)


def split_tail_mesh(source_path: Path, centre_origin_mm: np.ndarray) -> tuple[list[MeshInfo], list[float]]:
    source_tris = read_binary_stl(source_path)
    pts = source_tris.reshape(-1, 3)
    bbox_min = pts.min(axis=0)
    bbox_max = pts.max(axis=0)
    tail_center_mm = (bbox_min + bbox_max) / 2.0

    local_tail = transform_to_model(source_tris, tail_center_mm)
    tri_centers = local_tail.mean(axis=1)
    x_min = tri_centers[:, 0].min()
    x_max = tri_centers[:, 0].max()
    edges = np.linspace(x_max, x_min, TAIL_SEG_COUNT + 1)

    global_tail_center = transform_to_model(tail_center_mm.reshape(1, 3), centre_origin_mm).reshape(3)

    meshes: list[MeshInfo] = []
    global_centers: list[float] = []
    for idx in range(TAIL_SEG_COUNT):
        upper = edges[idx]
        lower = edges[idx + 1]
        if idx < TAIL_SEG_COUNT - 1:
            mask = (tri_centers[:, 0] <= upper) & (tri_centers[:, 0] > lower)
        else:
            mask = (tri_centers[:, 0] <= upper) & (tri_centers[:, 0] >= lower)
        seg_tris = local_tail[mask]
        if len(seg_tris) == 0:
            raise ValueError(f"tail segment {idx + 1} has no triangles")

        seg_pts = seg_tris.reshape(-1, 3)
        seg_bbox_min = seg_pts.min(axis=0)
        seg_bbox_max = seg_pts.max(axis=0)
        seg_center = (seg_bbox_min + seg_bbox_max) / 2.0
        seg_local = seg_tris - seg_center

        mesh_name = f"tail_seg{idx + 1}_mesh"
        file_name = f"{mesh_name}.stl"
        write_binary_stl(OUT_MESH_DIR / file_name, seg_local)
        info = mesh_info(mesh_name, file_name, seg_local)
        meshes.append(info)
        global_centers.append(float(global_tail_center[0] + seg_center[0]))

    return meshes, global_centers


def dynamic_box_geom(name: str, half_size: np.ndarray, mass: float) -> str:
    size = np.maximum(half_size, np.array([0.002, 0.002, 0.002], dtype=np.float64))
    return (
        f'<geom name="{name}_dyn" type="box" size="{vec3(size)}" '
        f'mass="{f(mass)}" rgba="0 0 0 0" contype="1" conaffinity="2" group="4"/>'
    )


def visual_mesh_geom(name: str, mesh_name: str, rgba: str) -> str:
    return (
        f'<geom name="{name}_vis" type="mesh" mesh="{mesh_name}" mass="0" '
        f'rgba="{rgba}" contype="0" conaffinity="0" group="1"/>'
    )


def mesh_asset_line(name: str, file_name: str) -> str:
    return f'<mesh name="{name}" file="{file_name}"/>'


def material_asset_line(name: str, rgba: str, **attrs: float | str) -> str:
    attr_text = " ".join(f'{key}="{value}"' for key, value in attrs.items())
    suffix = f" {attr_text}" if attr_text else ""
    return f'<material name="{name}" rgba="{rgba}"{suffix}/>'


def site_pair(prefix: str, x_offset: float) -> list[str]:
    return [
        f'<site name="{prefix}_left" pos="{vec3((x_offset, WIRE_RADIUS, 0.0))}"/>',
        f'<site name="{prefix}_right" pos="{vec3((x_offset, -WIRE_RADIUS, 0.0))}"/>',
    ]


def midpoint_joint_pos(body_pos_x: float) -> str:
    # Put the hinge at the midpoint between parent and child body centers.
    return vec3((-0.5 * body_pos_x, 0.0, 0.0))


def hinge_line(name: str, joint_class: str, body_pos_x: float, enabled: bool) -> list[str]:
    if not enabled:
        return []
    return [f'<joint name="{name}" class="{joint_class}" pos="{midpoint_joint_pos(body_pos_x)}"/>']


def build_pool_geoms() -> list[str]:
    wall_half_t = POOL_WALL_THICKNESS / 2.0
    floor_pos_z = -(POOL_HALF_DEPTH + wall_half_t)
    front_back_x = POOL_HALF_LENGTH + wall_half_t
    side_y = POOL_HALF_WIDTH + wall_half_t
    return [
        '<geom name="water_volume" type="box" '
        f'pos="{vec3((0.0, 0.0, 0.0))}" size="{vec3((POOL_HALF_LENGTH, POOL_HALF_WIDTH, POOL_HALF_DEPTH))}" '
        'material="water" contype="0" conaffinity="0" mass="0" group="2"/>',
        '<geom name="pool_floor" type="box" '
        f'pos="{vec3((0.0, 0.0, floor_pos_z))}" size="{vec3((POOL_HALF_LENGTH + wall_half_t, POOL_HALF_WIDTH + wall_half_t, wall_half_t))}" '
        'material="pool_wall" friction="0.8 0.1 0.1" contype="2" conaffinity="1"/>',
        '<geom name="pool_wall_front" type="box" '
        f'pos="{vec3((front_back_x, 0.0, 0.0))}" size="{vec3((wall_half_t, POOL_HALF_WIDTH, POOL_HALF_DEPTH))}" '
        'material="pool_wall" friction="0.8 0.1 0.1" contype="2" conaffinity="1"/>',
        '<geom name="pool_wall_back" type="box" '
        f'pos="{vec3((-front_back_x, 0.0, 0.0))}" size="{vec3((wall_half_t, POOL_HALF_WIDTH, POOL_HALF_DEPTH))}" '
        'material="pool_wall" friction="0.8 0.1 0.1" contype="2" conaffinity="1"/>',
        '<geom name="pool_wall_left" type="box" '
        f'pos="{vec3((0.0, side_y, 0.0))}" size="{vec3((POOL_HALF_LENGTH, wall_half_t, POOL_HALF_DEPTH))}" '
        'material="pool_wall" friction="0.8 0.1 0.1" contype="2" conaffinity="1"/>',
        '<geom name="pool_wall_right" type="box" '
        f'pos="{vec3((0.0, -side_y, 0.0))}" size="{vec3((POOL_HALF_LENGTH, wall_half_t, POOL_HALF_DEPTH))}" '
        'material="pool_wall" friction="0.8 0.1 0.1" contype="2" conaffinity="1"/>',
    ]


def classify_vertebrae(stl_paths: list[Path]) -> tuple[list[Path], list[float], list[Path], list[float], np.ndarray]:
    rows = []
    for path in stl_paths:
        tris = read_binary_stl(path)
        pts = tris.reshape(-1, 3)
        bbox_min = pts.min(axis=0)
        bbox_max = pts.max(axis=0)
        center = (bbox_min + bbox_max) / 2.0
        rows.append((path, center))

    # All rigid meshes share the same global X/Z centre. Use the compartment as the chain origin.
    centre_path = next(path for path, _ in rows if "centre_compartment" in path.name)
    centre_tris = read_binary_stl(centre_path)
    centre_pts = centre_tris.reshape(-1, 3)
    centre_bbox_min = centre_pts.min(axis=0)
    centre_bbox_max = centre_pts.max(axis=0)
    centre_origin = (centre_bbox_min + centre_bbox_max) / 2.0

    vertebra_rows = [(path, center) for path, center in rows if "back_v1-" in path.name]
    front = sorted(
        ((path, float(-(center[1] - centre_origin[1]) * 0.001)) for path, center in vertebra_rows if center[1] < centre_origin[1]),
        key=lambda item: item[1],
    )
    back = sorted(
        ((path, float(-(center[1] - centre_origin[1]) * 0.001)) for path, center in vertebra_rows if center[1] > centre_origin[1]),
        key=lambda item: abs(item[1]),
    )

    if len(front) != 9 or len(back) != 9:
        raise ValueError(f"expected 9 front and 9 back vertebrae, got {len(front)} front and {len(back)} back")

    front_paths, front_pos = zip(*front)
    back_paths, back_pos = zip(*back)
    return list(front_paths), list(front_pos), list(back_paths), list(back_pos), centre_origin


def build_tendon_block() -> list[str]:
    front_left = ['<spatial name="front_wire_left" width="0.0025" rgba="0.95 0.25 0.25 1">']
    front_left.append('  <site site="centre_front_left"/>')
    for idx in range(1, 10):
        front_left.append(f'  <site site="front_v{idx}_left"/>')
    front_left.append('  <site site="head_left"/>')
    front_left.append("</spatial>")

    front_right = ['<spatial name="front_wire_right" width="0.0025" rgba="0.85 0.18 0.18 1">']
    front_right.append('  <site site="centre_front_right"/>')
    for idx in range(1, 10):
        front_right.append(f'  <site site="front_v{idx}_right"/>')
    front_right.append('  <site site="head_right"/>')
    front_right.append("</spatial>")

    back_left = ['<spatial name="back_wire_left" width="0.0025" rgba="0.25 0.80 0.80 1">']
    back_left.append('  <site site="centre_back_left"/>')
    for idx in range(1, 10):
        back_left.append(f'  <site site="back_v{idx}_left"/>')
    back_left.append('  <site site="joint_tail_left"/>')
    back_left.append("</spatial>")

    back_right = ['<spatial name="back_wire_right" width="0.0025" rgba="0.18 0.68 0.68 1">']
    back_right.append('  <site site="centre_back_right"/>')
    for idx in range(1, 10):
        back_right.append(f'  <site site="back_v{idx}_right"/>')
    back_right.append('  <site site="joint_tail_right"/>')
    back_right.append("</spatial>")

    front_servo = [
        '<fixed name="front_servo_tendon">',
        f'  <joint joint="front_servo" coef="{f(SERVO_RADIUS)}"/>',
        "</fixed>",
    ]
    back_servo = [
        '<fixed name="back_servo_tendon">',
        f'  <joint joint="back_servo" coef="{f(SERVO_RADIUS)}"/>',
        "</fixed>",
    ]

    return [
        "<tendon>",
        *indent(front_left, 1),
        *indent(front_right, 1),
        *indent(back_left, 1),
        *indent(back_right, 1),
        *indent(front_servo, 1),
        *indent(back_servo, 1),
        "</tendon>",
    ]


def build_actuator_block() -> list[str]:
    return [
        "<actuator>",
        (
            f'  <position name="front_servo_act" joint="front_servo" '
            f'ctrlrange="-{f(SERVO_HALF_RANGE_RAD)} {f(SERVO_HALF_RANGE_RAD)}" kp="{f(SERVO_KP)}"/>'
        ),
        (
            f'  <position name="back_servo_act" joint="back_servo" '
            f'ctrlrange="-{f(SERVO_HALF_RANGE_RAD)} {f(SERVO_HALF_RANGE_RAD)}" kp="{f(SERVO_KP)}"/>'
        ),
        "</actuator>",
    ]


def build_sensor_block() -> list[str]:
    return [
        "<sensor>",
        '  <jointpos name="front_servo_pos_sensor" joint="front_servo"/>',
        '  <jointpos name="back_servo_pos_sensor" joint="back_servo"/>',
        '  <jointpos name="root_x_pos_sensor" joint="root_x"/>',
        '  <jointpos name="root_y_pos_sensor" joint="root_y"/>',
        '  <jointpos name="root_yaw_pos_sensor" joint="root_yaw"/>',
        '  <jointvel name="root_x_vel_sensor" joint="root_x"/>',
        '  <jointvel name="root_y_vel_sensor" joint="root_y"/>',
        '  <jointvel name="root_yaw_vel_sensor" joint="root_yaw"/>',
        '  <framepos name="head_pos" objtype="xbody" objname="head"/>',
        '  <framepos name="joint_tail_pos" objtype="xbody" objname="joint_tail"/>',
        '  <framexaxis name="centre_xaxis" objtype="xbody" objname="centre_compartment"/>',
        "</sensor>",
    ]


def build_equality_block() -> list[str]:
    return [
        "<equality>",
        (
            '  <tendon name="front_left_couple" tendon1="front_wire_left" '
            'tendon2="front_servo_tendon" polycoef="0 -1 0 0 0" '
            'solref="0.002 1" solimp="0.99 0.999 0.001"/>'
        ),
        (
            '  <tendon name="front_right_couple" tendon1="front_wire_right" '
            'tendon2="front_servo_tendon" polycoef="0 1 0 0 0" '
            'solref="0.002 1" solimp="0.99 0.999 0.001"/>'
        ),
        (
            '  <tendon name="back_left_couple" tendon1="back_wire_left" '
            'tendon2="back_servo_tendon" polycoef="0 -1 0 0 0" '
            'solref="0.002 1" solimp="0.99 0.999 0.001"/>'
        ),
        (
            '  <tendon name="back_right_couple" tendon1="back_wire_right" '
            'tendon2="back_servo_tendon" polycoef="0 1 0 0 0" '
            'solref="0.002 1" solimp="0.99 0.999 0.001"/>'
        ),
        "</equality>",
    ]


def main() -> None:
    stl_paths = sorted(MODEL_DIR.glob("*.STL"))
    if not stl_paths:
        raise FileNotFoundError("no STL files found in model directory")

    front_paths, front_global_x, back_paths, back_global_x, centre_origin_mm = classify_vertebrae(stl_paths)

    centre_path = next(path for path in stl_paths if "centre_compartment" in path.name)
    head_path = next(path for path in stl_paths if "head-1" in path.name)
    tail_joint_path = next(path for path in stl_paths if "tail_joint" in path.name)
    tail_path = next(path for path in stl_paths if "尾巴" in path.name or "tail-2" in path.name)

    OUT_MESH_DIR.mkdir(parents=True, exist_ok=True)

    centre_mesh = make_local_mesh(centre_path, "centre_compartment_mesh")
    vertebra_mesh = make_local_mesh(front_paths[0], "vertebra_mesh")
    head_mesh = make_local_mesh(head_path, "head_mesh")
    tail_joint_mesh = make_local_mesh(tail_joint_path, "tail_joint_mesh")
    tail_meshes, tail_global_x = split_tail_mesh(tail_path, centre_origin_mm)

    if vertebra_mesh.volume <= 0:
        raise ValueError("vertebra mesh volume must be positive")
    joint_material_density = VERTEBRA_MASS / vertebra_mesh.volume
    head_mass = joint_material_density * head_mesh.volume
    tail_joint_mass = joint_material_density * tail_joint_mesh.volume

    tail_total_volume = sum(mesh.volume for mesh in tail_meshes)
    if tail_total_volume <= 0:
        raise ValueError("tail mesh volume must be positive")
    tail_masses = [TAIL_TOTAL_MASS * mesh.volume / tail_total_volume for mesh in tail_meshes]

    centre_pts = read_binary_stl(centre_path).reshape(-1, 3)
    centre_bbox_min = centre_pts.min(axis=0)
    centre_bbox_max = centre_pts.max(axis=0)
    centre_head_x = float(-(centre_bbox_min[1] - centre_origin_mm[1]) * 0.001)
    centre_tail_x = float(-(centre_bbox_max[1] - centre_origin_mm[1]) * 0.001)

    head_pts = read_binary_stl(head_path).reshape(-1, 3)
    head_center_mm = (head_pts.min(axis=0) + head_pts.max(axis=0)) / 2.0
    head_global_x = float(transform_to_model(head_center_mm.reshape(1, 3), centre_origin_mm).reshape(3)[0])

    tail_joint_pts = read_binary_stl(tail_joint_path).reshape(-1, 3)
    tail_joint_center_mm = (tail_joint_pts.min(axis=0) + tail_joint_pts.max(axis=0)) / 2.0
    joint_tail_global_x = float(transform_to_model(tail_joint_center_mm.reshape(1, 3), centre_origin_mm).reshape(3)[0])

    asset_lines = [
        "<asset>",
        f'  {material_asset_line("pool_wall", "0.86 0.89 0.93 1", specular="0.2", shininess="0.2", reflectance="0.05")}',
        f'  {material_asset_line("water", "0.20 0.52 0.80 0.18", specular="0.1", shininess="0.05", reflectance="0.02")}',
        f'  {mesh_asset_line(centre_mesh.name, centre_mesh.file_name)}',
        f'  {mesh_asset_line(vertebra_mesh.name, vertebra_mesh.file_name)}',
        f'  {mesh_asset_line(head_mesh.name, head_mesh.file_name)}',
        f'  {mesh_asset_line(tail_joint_mesh.name, tail_joint_mesh.file_name)}',
    ]
    for mesh in tail_meshes:
        asset_lines.append(f'  {mesh_asset_line(mesh.name, mesh.file_name)}')
    asset_lines.append("</asset>")

    lines: list[str] = [
        '<mujoco model="eel_2d_stl_rebuild">',
        '  <compiler angle="degree" autolimits="true" inertiafromgeom="true" meshdir="generated_stl"/>',
        (
            f'  <option timestep="0.002" gravity="0 0 0" integrator="implicitfast" '
            f'cone="elliptic" iterations="100" density="{f(WATER_DENSITY)}" viscosity="{f(WATER_VISCOSITY)}"/>'
        ),
        "  <default>",
        '    <site type="sphere" size="0.004" rgba="0.90 0.20 0.20 1" group="3"/>',
        '    <default class="root_joint">',
        f'      <joint limited="false" stiffness="0" armature="{f(ROOT_ARMATURE)}" damping="{f(ROOT_DAMPING)}"/>',
        "    </default>",
        '    <default class="active_hinge">',
        (
            f'      <joint type="hinge" axis="0 0 1" limited="true" '
            f'range="-{f(ACTIVE_RANGE_DEG)} {f(ACTIVE_RANGE_DEG)}" '
            f'stiffness="{f(ACTIVE_STIFFNESS)}" damping="{f(ACTIVE_DAMPING)}" armature="0.0005"/>'
        ),
        "    </default>",
        '    <default class="tail_hinge">',
        (
            f'      <joint type="hinge" axis="0 0 1" limited="true" '
            f'range="-{f(TAIL_RANGE_DEG)} {f(TAIL_RANGE_DEG)}" '
            f'stiffness="{f(TAIL_STIFFNESS)}" damping="{f(TAIL_DAMPING)}" armature="0.0002"/>'
        ),
        "    </default>",
        '    <default class="tendon_motor">',
        '      <motor ctrllimited="true" ctrlrange="0 100" gear="1"/>',
        "    </default>",
        '    <default class="servo_joint">',
        (
            f'      <joint type="hinge" axis="0 0 1" limited="true" '
            f'range="-{f(SERVO_HALF_RANGE_DEG)} {f(SERVO_HALF_RANGE_DEG)}" damping="{f(SERVO_DAMPING)}" '
            f'armature="{f(SERVO_ARMATURE)}"/>'
        ),
        "    </default>",
        "  </default>",
        *asset_lines,
        "  <worldbody>",
        '    <light name="light" directional="true" diffuse="0.8 0.8 0.8" pos="0 0 2.5"/>',
        '    <camera name="top" pos="0 0 5.2" xyaxes="1 0 0 0 1 0"/>',
        '    <camera name="oblique" pos="-4.4 -3.4 2.2" xyaxes="0.65 -0.76 0 0.25 0.22 0.94"/>',
        *[f"    {line}" for line in build_pool_geoms()],
        '    <body name="front_servo_body" pos="0 0 0">',
        '      <joint name="front_servo" class="servo_joint"/>',
        '      <geom name="front_servo_geom" type="sphere" size="0.001" mass="1e-6" rgba="0 0 0 0" contype="0" conaffinity="0"/>',
        '    </body>',
        '    <body name="back_servo_body" pos="0 0 0">',
        '      <joint name="back_servo" class="servo_joint"/>',
        '      <geom name="back_servo_geom" type="sphere" size="0.001" mass="1e-6" rgba="0 0 0 0" contype="0" conaffinity="0"/>',
        '    </body>',
        '    <body name="centre_compartment" pos="0 0 0">',
        '      <joint name="root_x" class="root_joint" type="slide" axis="1 0 0"/>',
        '      <joint name="root_y" class="root_joint" type="slide" axis="0 1 0"/>',
        '      <joint name="root_yaw" class="root_joint" type="hinge" axis="0 0 1"/>',
        f'      {dynamic_box_geom("centre_compartment", centre_mesh.half_size, CENTRE_MASS)}',
        f'      {visual_mesh_geom("centre_compartment", centre_mesh.name, VISUAL_RGBA["centre"])}',
        '      <site name="centre_reference" pos="0 0 0" rgba="0 0 0 0"/>',
        f'      <site name="centre_front_left" pos="{vec3((centre_head_x, WIRE_RADIUS, 0.0))}"/>',
        f'      <site name="centre_front_right" pos="{vec3((centre_head_x, -WIRE_RADIUS, 0.0))}"/>',
        f'      <site name="centre_back_left" pos="{vec3((centre_tail_x, WIRE_RADIUS, 0.0))}"/>',
        f'      <site name="centre_back_right" pos="{vec3((centre_tail_x, -WIRE_RADIUS, 0.0))}"/>',
    ]

    # Front chain: closest vertebra to the compartment is front_v1.
    prev_x = 0.0
    for idx, global_x in enumerate(front_global_x, start=1):
        body_pos = global_x - prev_x
        body_lines = [
            f'<body name="front_v{idx}" pos="{vec3((body_pos, 0.0, 0.0))}">',
            *[f"  {line}" for line in hinge_line(f"front_v{idx}_yaw", "active_hinge", body_pos, idx not in FRONT_WELDED_CHILDREN)],
            f'  {dynamic_box_geom(f"front_v{idx}", vertebra_mesh.half_size, VERTEBRA_MASS)}',
            f'  {visual_mesh_geom(f"front_v{idx}", vertebra_mesh.name, VISUAL_RGBA["vertebra"])}',
            *[f"  {line}" for line in site_pair(f"front_v{idx}", 0.0)],
        ]
        lines.extend(
            indent(
                body_lines,
                3 + (idx - 1),
            )
        )
        prev_x = global_x

    head_rel = head_global_x - prev_x
    head_anchor_x = float(head_mesh.bbox_min[0] + 0.005)
    head_lines = [
        f'<body name="head" pos="{vec3((head_rel, 0.0, 0.0))}">',
        *[f"  {line}" for line in hinge_line("head_yaw", "active_hinge", head_rel, not HEAD_WELDED_TO_FRONT)],
        f'  {dynamic_box_geom("head", head_mesh.half_size, head_mass)}',
        f'  {visual_mesh_geom("head", head_mesh.name, VISUAL_RGBA["head"])}',
        '  <camera name="head_camera" pos="0.08 0 0.08" xyaxes="0 -1 0 0.34 0 0.94" fovy="120"/>',
        *[f"  {line}" for line in site_pair("head", head_anchor_x)],
    ]
    lines.extend(
        indent(
            head_lines,
            12,
        )
    )
    for level in reversed(range(3, 3 + len(front_global_x) + 1)):
        lines.extend(indent(["</body>"], level))

    # Back chain: closest vertebra to the compartment is back_v1.
    prev_x = 0.0
    for idx, global_x in enumerate(back_global_x, start=1):
        body_pos = global_x - prev_x
        body_lines = [
            f'<body name="back_v{idx}" pos="{vec3((body_pos, 0.0, 0.0))}">',
            *[f"  {line}" for line in hinge_line(f"back_v{idx}_yaw", "active_hinge", body_pos, idx not in BACK_WELDED_CHILDREN)],
            f'  {dynamic_box_geom(f"back_v{idx}", vertebra_mesh.half_size, VERTEBRA_MASS)}',
            f'  {visual_mesh_geom(f"back_v{idx}", vertebra_mesh.name, VISUAL_RGBA["vertebra"])}',
            *[f"  {line}" for line in site_pair(f"back_v{idx}", 0.0)],
        ]
        lines.extend(
            indent(
                body_lines,
                3 + (idx - 1),
            )
        )
        prev_x = global_x

    joint_tail_rel = joint_tail_global_x - prev_x
    # The back tendon should terminate on the proximal face of tail_joint,
    # i.e. the face closest to the back_v9 <-> joint_tail hinge.
    joint_tail_anchor_x = float(tail_joint_mesh.bbox_max[0] - 0.005)
    joint_tail_lines = [
        f'<body name="joint_tail" pos="{vec3((joint_tail_rel, 0.0, 0.0))}">',
        *[f"  {line}" for line in hinge_line("joint_tail_yaw", "active_hinge", joint_tail_rel, not JOINT_TAIL_WELDED_TO_BACK)],
        f'  {dynamic_box_geom("joint_tail", tail_joint_mesh.half_size, tail_joint_mass)}',
        f'  {visual_mesh_geom("joint_tail", tail_joint_mesh.name, VISUAL_RGBA["joint_tail"])}',
        *[f"  {line}" for line in site_pair("joint_tail", joint_tail_anchor_x)],
    ]
    lines.extend(
        indent(
            joint_tail_lines,
            12,
        )
    )

    prev_x = joint_tail_global_x
    for idx, (mesh, global_x, tail_mass) in enumerate(zip(tail_meshes, tail_global_x, tail_masses, strict=True), start=1):
        body_pos = global_x - prev_x
        lines.extend(
            indent(
                [
                    f'<body name="tail_seg{idx}" pos="{vec3((body_pos, 0.0, 0.0))}">',
                    f'  <joint name="tail_seg{idx}_yaw" class="tail_hinge" pos="{midpoint_joint_pos(body_pos)}"/>',
                    f'  {dynamic_box_geom(f"tail_seg{idx}", mesh.half_size, tail_mass)}',
                    f'  {visual_mesh_geom(f"tail_seg{idx}", mesh.name, VISUAL_RGBA["tail"])}',
                ],
                13 + (idx - 1),
            )
        )
        prev_x = global_x

    for depth in reversed(range(1 + len(tail_meshes))):
        lines.extend(indent(["</body>"], 12 + depth))
    for depth in reversed(range(9)):
        lines.extend(indent(["</body>"], 3 + depth))

    lines.extend(
        [
            "    </body>",
            "  </worldbody>",
            *indent(build_tendon_block(), 1),
            *indent(build_equality_block(), 1),
            *indent(build_actuator_block(), 1),
            *indent(build_sensor_block(), 1),
            "</mujoco>",
        ]
    )

    OUT_XML.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT_XML}")
    print(f"Wrote meshes to {OUT_MESH_DIR}")

    from split_fish_pool_mjcf import main as split_main

    split_main()


if __name__ == "__main__":
    main()
